Network config
bearing/dosenet-raspberrypi pull request #85
Opened 2016-12-08 04:28 UTC by yarocoder

Major update and rewrite of the network configuration file into the Python scripting language for accessibility, readability, and update-ability. Copying the config.csv file from the LBL servers to the Pi hat is successfully working.

Updating the station ID on the network interfaces file still needs work. It is near full functionality but hasn't been fully tested/debugged. It is expected that the last update to the code will work fully, but it needs to be tested. METHOD 1 in the interfacesUpdate function is short, simple, and sweet but does not work! The interfaces file is left blank, suggesting a root access problem of copying the interfaces problem even with the use of the sudo command, similar to what METHOD 2 had before that was debugged. METHOD 2 fully worked before extra functionality was added (explained later in this description). Now the raw_input functions simply print the statement they are asking of the user and does not return the input from the user! Saving and returning the standard input was added just now to address this, but has not been tested yet. So METHOD 2 will most likely be utilized after full testing and debugging. (Note: There are two random print statements in the code that print the input from the user. They were used for debugging.)

The extra functionality that this script will have over the bash network configuration script is that it adds the ability to add a static IP and netmask, gateway, and DNS server identifiers. This is a relatively simple addition, but the interfacesUpdate function must work for this extra functionality to work.

2016-12-08 23:23 UTC, bplimley requested changes
Hi Yaro, thanks for working on this.
We try to keep a consistent code "style" (by which I mean, the formatting of code and comments, rather than how the code actually works). As you get used to a consistent style, it makes code easier to read, easier to understand, and easier to catch errors or bugs.

We mostly follow standard Python style as documented in [PEP8](https://www.python.org/dev/peps/pep-0008/) and also the [Google Python style guide](https://google.github.io/styleguide/pyguide.html).

So there are quite a few things to adjust in your code. I know we haven't necessarily discussed it specifically before.

In particular, check:
* Line length (no more than 79 characters) (use parantheses and implicit line joining) (break strings using 'asdf' + 'asdf' as needed)
* Variable and function names (should be lowercase, with words separated by underscores if needed)

If you use Atom text editor, the `flake8` package will catch a lot of style issues for you. Flake8 should be available for Sublime Text or others too.

2016-12-08 23:23 UTC, bplimley commented on station-update.py
> +os.system('sudo scp "%s" "%s"' % (sourcePath, targetPath))
Also, use `.format()` instead of `%` for string formatting.

2017-01-23 22:47 UTC, yarocoder commented
Hi Brian, the code should be updated now! Just tested and fully working in PEP8 style.

2017-01-23 23:46 UTC, alihanks commented on station-update.py
> +os.system('sudo scp {} {}'.format(sourcePath, targetPath))
I think you probably don't want to use sudo here. The file you copy from the server should be owned by the pi user, not root. I doubt this would actually cause problems for our code, since it all runs under sudo, but it isn't necessary.

2017-01-23 23:46 UTC, alihanks commented on station-update.py
> +
I would put your function definition at the beginning or end of the file, rather than in the middle like this. It's odd to interrupt the flow of the script itself with the function definition.

2017-01-23 23:46 UTC, alihanks commented on station-update.py
> +if setup_static_ip is 'y':
May want to make this slightly more robust by making the check on 'y' case insensitive (there is a .lower() method for strings you can use), also, set a default for setup_static_ip, the default should be no. 

That suggestion applies to all the following yes/no questions you ask. You should have a default response. You should indicate what the default is in the user prompt as well.

2017-01-23 23:46 UTC, alihanks commented on station-update.py
> +
Also, I would suggest checking first if the response is 'n' (again without case sensitivity) and exiting the script at this point if it is. There is no need to prompt for all the other inputs if the user does not want to set a static IP. Here and at the end of the script after the other input prompts, you should print out something confirming the status, i.e. that you are done modifying the interfaces file with a dynamic IP or that the static IP has been set, etc.

2017-01-23 23:46 UTC, alihanks commented on station-update.py
> +
See earlier comments about exiting before all the IP queries if the user says 'n' to wanting to set the static IP, you could consider asking about restoring the backup within that context as well. 

I would switch the question, though, and ask something like 'Would you like to keep these changes', make the default yes, and if they say no then restore the backup.

2017-02-03 18:26 UTC, yarocoder commented
The code is now fully tested and working. All issues have been addressed.

2017-02-15 18:01 UTC, alihanks approved these changes

2017-03-07 00:14 UTC, merged